name: "Publish stripped voltron.txt"

on:
  push:
    branches:
      - master
      - automation
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v3
      - name: Checkout master branch into a subdir
        uses: actions/checkout@v3
        with:
          ref: master
          path: master
      - name: Fetch Destiny 2 item database
        run: ./fetch_manifest.sh manifest.json
      - name: Setup Go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Generate new wishlist with perks only from 3rd and 4th columns
        run: go run strip.go --manifest=manifest.json --wishlist=master/voltron.txt > voltron.txt
      # - name: Upload generated wishlist to artifact storage
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: voltron
      #     path: voltron.txt
      # - name: Deploy generated wishlist to pages
      #   uses: actions/deploy-pages@v1
      - name: Checkout generated branch into a subdir
        uses: actions/checkout@v3
        with:
          ref: generated
          path: generated
      - name: Commit voltron.txt into generated branches
        run: |
          cp voltron.txt generated/
          cd generated
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add voltron.txt
          git commit -m 'Update voltron.txt'
          git push
