name: "Publish stripped voltron.txt"

on:
  push:
    branches:
      - automation
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/pull.yml'
      - '**.md'
  schedule:
    - cron: "27 0 * * *"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Checkout master branch into a subdir
        uses: actions/checkout@v3
        with:
          ref: master
          path: master
      - name: Fetch Destiny 2 item database
        run: ./fetch_manifest.sh manifest.json
      - name: Setup Go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Generate new wishlist with perks only from 3rd and 4th columns
        run: |
          go run strip.go --manifest=manifest.json \
            --wishlist=master/voltron.txt \
            --set_title="Stripped voltron" \
            --set_description="DIM's default wishlist, but with perks only from 3rd and 4th column. https://github.com/imax9000/dim-wish-list-sources/" \
            > voltron.txt
      - name: Generate new wishlist with perks only from 3rd and 4th columns
        run: |
          go run strip.go --manifest=manifest.json \
            --wishlist=master/voltron.txt \
            --set_title="Stripped voltron" \
            --set_description="DIM's default wishlist, but with perks only from 3rd and 4th column. https://github.com/imax9000/dim-wish-list-sources/" \
            --append_to_notes=" [3rd&4th columns only]" \
            > voltron_flagged.txt
      - name: Checkout generated branch into a subdir
        uses: actions/checkout@v3
        with:
          ref: generated
          path: generated
      - name: Commit wishlists into generated branch
        run: |
          cp *.txt generated/
          cd generated
          git config user.name automation
          git config user.email github-actions@github.com
          git add *.txt
          if ! git diff-index --quiet HEAD; then
            git commit -m 'Update generated files'
            git push
          fi
